### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by iiLearner** [m1n1vv/UICompass#1]
Hello,

I've seen your include file and the example code, i don't get a few things such as: 
In your example code there's "UICOMPASS_STEP" which is not defined at all, and then there are textdraws they ain't defined either. do we have to create the textdraws? and the variables?

Do you mind explaining a bit

**Comment by iiLearner** [comment]
bump

**Comment by m1n1vv** [comment]
Fixed 11 days ago.
[Example](https://github.com/m1n1vv/UICompass/wiki/Example-EN)
